# Generated by Django 5.2.4 on 2025-07-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='contact',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
    ]
