services:
  - type: web
    name: carnet-contacts
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn carnet.wsgi:application"
    envVars:
    - key: DJANGO_SETTINGS_MODULE
    value: carnet.settings

      - key: PYTHON_VERSION
        value: 3.11
